### ISSUE TITLE
Inconsistent player info states

### ISSUE THREAD

**Issue by RealPortalPlayer** [NepNep21/MSA4Legacy#10]
The player info state (the play button, and the welcome text) are acting inconsistently.

I noticed one of these three would happen:

- It would work perfectly fine
- It would say "Play" but also say "Welcome, guest! Please log in."
![Says play, but also acts like you're not logged in](https://github.com/NepNep21/MSA4Legacy/assets/20852986/4604bb79-8905-4f11-9f5b-5a29b4ecfe5a)
- The button never stops saying "Loading...", and the side text says "Welcome, guest! Please log in."
![Stuck saying loading, stays like this until you select a different profile](https://github.com/NepNep21/MSA4Legacy/assets/20852986/87387d4c-028d-4dc7-aace-33766d049fb6)

If it's the second, or third one, then selecting a different profile would typically fix it. The second one still lets you play, even though the side text says you're not logged in.

Due to it being inconsistent, this feels very much like a race condition.

**Comment by NepNep21** [comment]
Hard to reproduce, can you check if this helps? https://github.com/NepNep21/MSA4Legacy/actions/runs/6372362489

**Comment by RealPortalPlayer** [comment]
That seemed to have fixed it, I guess there's something wrong with my JDK installation
