### ISSUE TITLE
Doesn't seem to function properly

### ISSUE THREAD

**Issue by SystemZeta** [NepNep21/MSA4Legacy#4]
I followed the instructions in the README and I got an error because patches.lzma wasn't found in my home directory. Ok, I git clones and ran `tar -cf patches.lzma --lzma patches/*` and copied the lzma  file I got into my home directory, reran the installer and it worked. Launched the "patched" launcher and I couldn't log in. Please fix this.

**Comment by SystemZeta** [comment]
generated patches from github. that works

**Comment by toydotgame** [comment]
I don't think you should have needed to un-LZMA the patches file. The patcher JAR seemed to only work with a `patches.lzma` file, from my testing.
