### ISSUE TITLE
Launcher straight up stalls after first step of login. Not unresponsive but not working either.

### ISSUE THREAD

**Issue by Safariminer** [NepNep21/MSA4Legacy#5]
So, I was trying to use the launcher, and log in, but then nothing worked. I clicked on "Microsoft Account", put in my email, clicked "Log In", and there was a text saying to go to a website and enter a code. So far so good. When, though, I entered said code, nothing happened. The website said that I was logged in "Nepauth", but the launcher did nothing. I could still press the buttons, but that's it. As of right now, the "Log In" button does nothing and I cannot log in.

Tried:
- Redownloading the patch file, on multiple versions
- Redownloading the launcher
- Redownloading the installer
- Restarting the launcher several times
- Killing Java and restarting it.

Am I doing something wrong or is there a problem with the launcher.

**Comment by NepNep21** [comment]
Start the launcher from a command line and send the output

**Comment by Safariminer** [comment]
So, I ran ```java -jar launcher-patched.jar > log.txt``` and it gave me two separate things.
First, the command line gave me this message: 
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```


Next, the "> log.txt" gave me this output: https://pastebin.com/dnm4dh8r

**Comment by NepNep21** [comment]
> XSTS auth returned 401 with XErr 2148916238

This can mean one of 2 things:
1. Your account is set as <18 and not linked to a family, only the official launcher can log in such accounts, you can either link it to another account, that must be 18+ but does not necessarily have to own the game, or you can set your account age as higher
2. The other possibility is that it's a bug in the microsoft auth system, i have seen it say that accounts aren't 18+ when they actually are, in that case i don't know a solution

**Comment by Safariminer** [comment]
Oh, ok, thanks. Microsoft's age system is truly terrible for a lot of reasons.

**Comment by toydotgame** [comment]
I had roughly the same issue. M$ account age is brokey asf.
