### ISSUE TITLE
The installer is missing error message/popup when not all requirements are met

### ISSUE THREAD

**Issue by Lassebq** [NepNep21/MSA4Legacy#7]
![image](https://user-images.githubusercontent.com/68742864/223220266-da2b854f-7f92-4c36-9640-86fd538d566f.png)
After selecting the launcher.jar and clicking "Save" file select window closes and the "Select launcher jar to install"
stays.

**Comment by Lassebq** [comment]
Nevermind, the patches needed to be in the same directory.

**Comment by Lassebq** [comment]
Ok, actually, gonna reopen this with a different title

**Comment by NepNep21** [comment]
That is true, the installer was kinda messily put together, I will look into it at some point.
