### ISSUE TITLE
Modded Jars Won't Launch

### ISSUE THREAD

**Issue by Schnyarf** [NepNep21/MSA4Legacy#8]
Modifying [version].json by removing all of the contents following "MinimumLauncherVersion: 4" is supposed to prevent the launcher from attempting to overwrite the version's .jar file. For some reason, when trying to run my old modified .jar versions from prior to migration, the launcher hangs at "Downloading [version].jar," even though it's been told not to.

I hope to high heaven that this behavior isn't forced by Microsoft, I wouldn't have migrated if I knew this was going to happen.

**Comment by NepNep21** [comment]
The authentication method is irrelevant for a bug like that one, as the content repository doesn't require a token at all, and above all else that is a launcher behavior bug since it shouldn't even be downloading anything. I will look into it.

**Comment by Schnyarf** [comment]
Ah, thank you. And I should also apologize for my somewhat frantic tone. I've been a 1.6 launcher holdout for years now, and I finally folded and migrated my account when I found out about this project, and I was scared because I was frantically trying to figure out how to get my favorite versions working again.

I really appreciate the work that you've done with this project.

**Comment by NepNep21** [comment]
The bug seems to be 2-fold:
- The version manifest is updated even when it doesn't need to.
- The version jar is updated even if the hash from the manifest is empty/missing.
I feel I am very close to fixing it but I will continue working on it tomorrow (or when I have time after that).

**Comment by NepNep21** [comment]
I think https://github.com/NepNep21/MSA4Legacy/actions/runs/4974341988 should fix it, though specifically I recommend setting the hash of the client jar (screenshot attached) to an empty string rather than indiscriminately deleting fields, deleting things may also work though. Please report whether my fix works, and if it does I will merge it into the main branch.
![image](https://github.com/NepNep21/MSA4Legacy/assets/43792621/0bff4b58-2cca-47be-8934-032e70a3cd39)

**Comment by NepNep21** [comment]
@Schnyarf Please test that build so I can merge it.

**Comment by Schnyarf** [comment]
I'm not sure how to download the updated binaries, but I have found that your initial suggestion appears to work.

**Comment by NepNep21** [comment]
The binaries are in the "artifacts" section of the link.

**Comment by Schnyarf** [comment]
I have since discovered that the issue appears to be linked to the fetching of assets. The original 1.6 launcher could handle it when "assetIndex" was absent, but this modified one cannot. Testing the build now.

**Comment by NepNep21** [comment]
Deleting key-value pairs that "come after <another pair>" in JSON is inherently unreliable, JSON does not require implementations to make any guarantees about what's before or after something else within an object, for all we know there are just different things after it than what you're used to. Regardless, setting a value to another value (in this case an empty string) is not undefined behavior of course, so setting the hash to an empty one is what will be worked on if it doesn't work, not deleting random pairs.

Also I don't recommend editing comments to notify someone on github about results, as it does not cause github to email us :p

**Comment by Schnyarf** [comment]
While I don't know what is causing this launcher to behave differently from the vanilla one, I have figured out how to get the launcher to respect both my custom .jars as well as my custom assets directories, so this issue no longer bothers me.
