### ISSUE TITLE
The launcher pesters for login every time it is opened

### ISSUE THREAD

**Issue by Schnyarf** [NepNep21/MSA4Legacy#9]
Every time I open the launcher, I am prompted with the user switcher screen that asks if I want to use the previous account or switch to a different one. I'm not aware of why this launcher has such trouble with saving the login session like the vanilla one did with the Mojang accounts, but it is quite annoying every time I want to play the game.

**Comment by NepNep21** [comment]
Fixed by accaf2e3cb9faed35b4ab74cf4bfe379b1a77829
